### ISSUE TITLE
Fails to compile with template-haskell-2.11

### ISSUE THREAD

**Issue by hvr** [dreixel/regular#3]
```
[ 4 of 15] Compiling Generics.Regular.TH ( src/Generics/Regular/TH.hs, dist/dist-sandbox-2d4eb5d5/build/Generics/Regular/TH.o )

src/Generics/Regular/TH.hs:95:15: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ n _ cs _
      In the pattern: TyConI (DataD _ n _ cs _)
      In a case alternative: TyConI (DataD _ n _ cs _) -> mkInstance n cs

src/Generics/Regular/TH.hs:109:15: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ n _ cs _
      In the pattern: TyConI (DataD _ n _ cs _)
      In a case alternative: TyConI (DataD _ n _ cs _) -> mkInstance n cs

src/Generics/Regular/TH.hs:123:24: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ _ tv _ _
      In the pattern: TyConI (DataD _ _ tv _ _)
      In an equation for ‘typeVariables’:
          typeVariables (TyConI (DataD _ _ tv _ _)) = tv

src/Generics/Regular/TH.hs:146:3: error:
    • Couldn't match expected type ‘Q Dec’
                  with actual type ‘CxtQ -> DecQ’
    • Probable cause: ‘dataD’ is applied to too few arguments
      In the expression: dataD (cxt []) (genName [dt, n]) [] [] []
      In an equation for ‘mkConstrData’:
          mkConstrData dt (NormalC n _)
            = dataD (cxt []) (genName [dt, n]) [] [] []

src/Generics/Regular/TH.hs:146:39: error:
    • Couldn't match expected type ‘Maybe Kind’ with actual type ‘[t3]’
    • In the fourth argument of ‘dataD’, namely ‘[]’
      In the expression: dataD (cxt []) (genName [dt, n]) [] [] []
      In an equation for ‘mkConstrData’:
          mkConstrData dt (NormalC n _)
            = dataD (cxt []) (genName [dt, n]) [] [] []

src/Generics/Regular/TH.hs:153:33: error:
    • Couldn't match type ‘Cxt -> Dec’ with ‘Dec’
      Expected type: Q [Dec]
        Actual type: Q [Cxt -> Dec]
    • In the expression: return (map one fs)
      In an equation for ‘mkSelectData’:
          mkSelectData dt r@(RecC n fs)
            = return (map one fs)
            where
                one (f, _, _) = DataD [] (genName [dt, ....]) [] [] []

src/Generics/Regular/TH.hs:154:58: error:
    • Couldn't match expected type ‘Maybe Kind’ with actual type ‘[t0]’
    • In the fourth argument of ‘DataD’, namely ‘[]’
      In the expression: DataD [] (genName [dt, n, f]) [] [] []
      In an equation for ‘one’:
          one (f, _, _) = DataD [] (genName [dt, n, f]) [] [] []

src/Generics/Regular/TH.hs:174:18: error:
    • The constructor ‘DataConI’ should have 3 arguments, but has been given 4
    • In the pattern: DataConI _ _ _ f
      In a case alternative: DataConI _ _ _ f -> convertFixity f
      In the expression:
        case i of {
          DataConI _ _ _ f -> convertFixity f
          _ -> Prefix }

src/Generics/Regular/TH.hs:191:37: error:
    • Couldn't match type ‘[Dec] -> Dec’ with ‘Dec’
      Expected type: Q [Dec]
        Actual type: Q [[Dec] -> Dec]
    • In the expression: return (map one fs)
      In an equation for ‘mkSelectInstance’:
          mkSelectInstance dt r@(RecC n fs)
            = return (map one fs)
            where
                one (f, _, _)
                  = InstanceD
                      ([])
                      (AppT (ConT ''Selector) (ConT $ genName [dt, ....]))
                      [FunD ... ...]

src/Generics/Regular/TH.hs:194:18: error:
    • Couldn't match expected type ‘Maybe Overlap’
                  with actual type ‘[t2]’
    • In the first argument of ‘InstanceD’, namely ‘([])’
      In the expression:
        InstanceD
          ([])
          (AppT (ConT ''Selector) (ConT $ genName [dt, n, f]))
          [FunD
             'selName [Clause [...] (NormalB (LitE (StringL (nameBase f)))) []]]
      In an equation for ‘one’:
          one (f, _, _)
            = InstanceD
                ([])
                (AppT (ConT ''Selector) (ConT $ genName [dt, n, f]))
                [FunD
                   'selName [Clause ... (NormalB (LitE (StringL (nameBase f)))) ...]]

src/Generics/Regular/TH.hs:194:23: error:
    • Couldn't match type ‘Type’ with ‘[Pred]’
      Expected type: Cxt
        Actual type: Type
    • In the second argument of ‘InstanceD’, namely
        ‘(AppT (ConT ''Selector) (ConT $ genName [dt, n, f]))’
      In the expression:
        InstanceD
          ([])
          (AppT (ConT ''Selector) (ConT $ genName [dt, n, f]))
          [FunD
             'selName [Clause [...] (NormalB (LitE (StringL (nameBase f)))) []]]
      In an equation for ‘one’:
          one (f, _, _)
            = InstanceD
                ([])
                (AppT (ConT ''Selector) (ConT $ genName [dt, n, f]))
                [FunD
                   'selName [Clause ... (NormalB (LitE (StringL (nameBase f)))) ...]]

src/Generics/Regular/TH.hs:195:9: error:
    • Couldn't match expected type ‘Type’ with actual type ‘[Dec]’
    • In the third argument of ‘InstanceD’, namely
        ‘[FunD
            'selName
            [Clause [...] (NormalB (LitE (StringL (nameBase f)))) []]]’
      In the expression:
        InstanceD
          ([])
          (AppT (ConT ''Selector) (ConT $ genName [dt, n, f]))
          [FunD
             'selName [Clause [...] (NormalB (LitE (StringL (nameBase f)))) []]]
      In an equation for ‘one’:
          one (f, _, _)
            = InstanceD
                ([])
                (AppT (ConT ''Selector) (ConT $ genName [dt, n, f]))
                [FunD
                   'selName [Clause ... (NormalB (LitE (StringL (nameBase f)))) ...]]

src/Generics/Regular/TH.hs:204:25: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ dt vs cs _
      In the pattern: TyConI (DataD _ dt vs cs _)
      In a case alternative:
          TyConI (DataD _ dt vs cs _)
            -> foldr1 sum (map (pfCon (dt, map tyVarBndrToName vs)) cs)

src/Generics/Regular/TH.hs:255:25: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ dt vs cs _
      In the pattern: TyConI (DataD _ dt vs cs _)
      In a case alternative:
          TyConI (DataD _ dt vs cs _)
            -> zipWith
                 (fromCon wrapE ns (dt, map tyVarBndrToName vs) (length cs))
                 [0 .. ]
                 cs

src/Generics/Regular/TH.hs:271:25: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ dt vs cs _
      In the pattern: TyConI (DataD _ dt vs cs _)
      In a case alternative:
          TyConI (DataD _ dt vs cs _)
            -> zipWith
                 (toCon wrapP ns (dt, map tyVarBndrToName vs) (length cs))
                 [0 .. ]
                 cs
xcabal: Error: some packages failed to install:
regular-0.3.4.4 failed during the building phase. The exception was:
ExitFailure 1
```
